url: http://natops.github.io
baseurl:

# Site Settings
title: Natalia Raythz
description: "Timeline is multipurpose, single page Jekyll theme that includes a timeline section."
keywords: "jekyll, theme"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/nanababy.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]
